name: 'Latest Docker Image - main'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'tests/**'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Ls
        run: ls -alh
      - name: Build
        run: |
          npm install
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: admgo/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}